# -*- coding: utf-8 -*-
"""I.A de Cópia de NICOLAU Analisador de sentimentos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpxuOB87mQpXPp55rbXmVXzp-LjcFxbZ
"""

"""
ANALISADOR DE SENTIMENTOS COM IA
Análise de sentimentos usando modelo Transformer pré-treinado
Autor: Turma de Engenharia de Software
Versão: 2.0 (Refatorada)
"""

from transformers import pipeline
from typing import Optional, Dict
import sys


class AnalisadorSentimentos:
    """Classe para análise de sentimentos usando modelo de IA."""

    MODELO_ID = "pysentimiento/bertweet-pt-sentiment"

    # Mapeamento de labels para descrições em português
    SENTIMENTOS = {
        'POS': {'emoji': '😊', 'texto': 'POSITIVO'},
        'NEG': {'emoji': '😞', 'texto': 'NEGATIVO'},
        'NEU': {'emoji': '😐', 'texto': 'NEUTRO'}
    }

    def __init__(self):
        """Inicializa o analisador (modelo será carregado sob demanda)."""
        self._analisador = None

    def carregar_modelo(self) -> bool:
        """
        Carrega o modelo de IA.

        Returns:
            bool: True se carregado com sucesso, False caso contrário
        """
        try:
            print("\n" + "="*60)
            print("🤖 Carregando modelo de Inteligência Artificial...")
            print(f"📦 Modelo: {self.MODELO_ID}")
            print("⏳ Aguarde, pode levar alguns segundos...")
            print("="*60)

            self._analisador = pipeline(
                "sentiment-analysis",
                model=self.MODELO_ID
            )

            print("✅ Modelo carregado com sucesso!\n")
            return True

        except Exception as e:
            print(f"❌ Erro ao carregar modelo: {e}")
            return False

    def analisar(self, frase: str) -> Optional[Dict]:
        """
        Analisa o sentimento de uma frase.

        Args:
            frase: Texto a ser analisado

        Returns:
            Dicionário com label e score, ou None em caso de erro
        """
        if self._analisador is None:
            print("❌ ERRO: Modelo não foi carregado!")
            return None

        if not frase or not frase.strip():
            print("⚠️ Frase vazia não pode ser analisada!")
            return None

        try:
            resultado = self._analisador(frase.strip())[0]
            return resultado
        except Exception as e:
            print(f"❌ Erro na análise: {e}")
            return None

    def exibir_resultado(self, frase: str, resultado: Dict) -> None:
        """
        Exibe o resultado da análise de forma formatada.

        Args:
            frase: Texto analisado
            resultado: Dicionário retornado pela IA
        """
        print("\n" + "="*60)
        print("📊 RESULTADO DA ANÁLISE")
        print("="*60)
        print(f'💬 Frase: "{frase}"')
        print("-"*60)

        label = resultado['label']
        confianca = resultado['score']

        sentimento = self.SENTIMENTOS.get(label, {'emoji': '❓', 'texto': 'DESCONHECIDO'})

        print(f"{sentimento['emoji']} Sentimento: {sentimento['texto']}")
        print(f"📈 Confiança: {confianca * 100:.2f}%")
        print("="*60)


class Menu:
    """Classe para gerenciar o menu interativo."""

    def __init__(self, analisador: AnalisadorSentimentos):
        """
        Inicializa o menu.

        Args:
            analisador: Instância do AnalisadorSentimentos
        """
        self.analisador = analisador

    def exibir_menu(self) -> None:
        """Exibe as opções do menu."""
        print("\n" + "="*60)
        print("📋 MENU PRINCIPAL")
        print("="*60)
        print("1️⃣  Analisar uma frase")
        print("2️⃣  Analisar múltiplas frases")
        print("3️⃣  Sobre o modelo de IA")
        print("4️⃣  Sair")
        print("="*60)

    def opcao_analisar_frase(self) -> None:
        """Opção para analisar uma única frase."""
        print("\n" + "-"*60)
        frase = input("💬 Digite a frase para análise: ").strip()

        if not frase:
            print("⚠️ Nenhuma frase foi digitada!")
            return

        resultado = self.analisador.analisar(frase)
        if resultado:
            self.analisador.exibir_resultado(frase, resultado)

    def opcao_analisar_multiplas(self) -> None:
        """Opção para analisar múltiplas frases."""
        print("\n" + "-"*60)
        print("📝 Digite as frases (uma por linha)")
        print("💡 Digite 'FIM' quando terminar")
        print("-"*60)

        frases = []
        while True:
            frase = input(f"Frase {len(frases) + 1}: ").strip()

            if frase.upper() == 'FIM':
                break

            if frase:
                frases.append(frase)

        if not frases:
            print("⚠️ Nenhuma frase foi digitada!")
            return

        print(f"\n🔍 Analisando {len(frases)} frase(s)...\n")

        for i, frase in enumerate(frases, 1):
            resultado = self.analisador.analisar(frase)
            if resultado:
                print(f"\n--- Análise {i}/{len(frases)} ---")
                self.analisador.exibir_resultado(frase, resultado)

    def opcao_sobre_modelo(self) -> None:
        """Exibe informações sobre o modelo."""
        print("\n" + "="*60)
        print("ℹ️  SOBRE O MODELO")
        print("="*60)
        print(f"🤖 Modelo: {AnalisadorSentimentos.MODELO_ID}")
        print("📚 Tipo: Transformer (BERT)")
        print("🌍 Idioma: Português")
        print("🎯 Tarefa: Análise de Sentimentos")
        print("\n💡 Como funciona:")
        print("   • Modelo pré-treinado com milhares de exemplos")
        print("   • Entende contexto e nuances da linguagem")
        print("   • Não precisa de dicionário manual de palavras")
        print("   • Retorna confiança da predição (0-100%)")
        print("="*60)

    def executar(self) -> None:
        """Loop principal do menu."""
        while True:
            self.exibir_menu()
            opcao = input("👉 Escolha uma opção (1-4): ").strip()

            if opcao == "1":
                self.opcao_analisar_frase()

            elif opcao == "2":
                self.opcao_analisar_multiplas()

            elif opcao == "3":
                self.opcao_sobre_modelo()

            elif opcao == "4":
                print("\n" + "="*60)
                print("👋 Obrigado por usar o Analisador de Sentimentos!")
                print("="*60 + "\n")
                sys.exit(0)

            else:
                print("\n⚠️ Opção inválida! Escolha entre 1 e 4.")


def main():
    """Função principal do programa."""
    print("="*60)
    print("💙 ANALISADOR DE SENTIMENTOS COM IA")
    print("="*60)

    # Inicializar analisador
    analisador = AnalisadorSentimentos()

    # Carregar modelo
    if not analisador.carregar_modelo():
        print("❌ Não foi possível iniciar o programa.")
        sys.exit(1)

    # Iniciar menu
    menu = Menu(analisador)
    menu.executar()


if __name__ == "__main__":
    main()